spring:
  datasource:
    url: jdbc:postgresql://ec2-35-168-194-15.compute-1.amazonaws.com:5432/dadnlbdbp80u6h
    username: kiekrcbnosfqeh
    password: cbd12b7368503d510c87d186e04538e735cf71cff6a496511433560133225460
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true

  # h2:
  #   console:
  #     enabled: true
  #     path: /h2




# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driverClassName=org.h2.Driver
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
